# Generated by Django 5.0.3 on 2024-04-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipee_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipee',
            name='image',
            field=models.ImageField(upload_to='uploaded'),
        ),
    ]
