# Generated by Django 5.0.3 on 2024-04-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipee_app', '0003_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='login',
        ),
    ]
